name: linktinger_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
  http: ^1.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  path: ^1.9.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0  # ✅ الأحدث والمتوافقة مع FCM

  flip_card: ^0.7.0
  timeago: ^3.6.0
  web_socket_channel: ^3.0.3
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  image_picker: 1.1.2
  fluttertoast: ^8.2.12
  mime: ^2.0.0
  http_parser: ^4.0.2
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  record: ^6.0.0
  just_audio: ^0.10.4
  permission_handler: ^12.0.1
  camera: 0.10.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^3.1.0
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_bg.png
    - assets/images/logo.png
    - assets/images/logo1.png
    - assets/images/user1.jpg
    - assets/images/user2.jpg
    - assets/images/user3.jpg
    - assets/images/user4.jpg
    - assets/images/post1.jpg
    - assets/images/post2.jpg
    - assets/images/profile.png
