platform :ios, '14.0'

use_frameworks! :linkage => :static
use_modular_headers!

# Flutter helper (يضيف إعدادات Flutter للـ Pods)
flutter_root = ENV['FLUTTER_ROOT']
require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'))

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      # توحيد الحد الأدنى + إلغاء Bitcode لتوافق iOS 17+
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
